const $ = selector => document.querySelector(selector);
const fields = (values, definitions) => definitions.map(([key,label,type='text',wide=false]) => `<label class="${wide?'wide':''}">${label}${type==='textarea'?`<textarea data-key="${key}">${escapeHtml(values[key]??'')}</textarea>`:`<input data-key="${key}" type="${type}" value="${escapeHtml(values[key]??'')}">`}</label>`).join('');
const escapeHtml = value => String(value).replace(/[&<>"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
let data, selectedNation, selectedRegion, dirty=false;

const backendOrigin=!location.protocol.startsWith('http')?'http://127.0.0.1:3000':['localhost','127.0.0.1'].includes(location.hostname)&&location.port!=='3000'?`${location.protocol}//${location.hostname}:3000`:location.origin;
async function request(url, options={}) { const response=await fetch(`${backendOrigin}${url}`,{headers:{'Content-Type':'application/json'},...options}); const type=response.headers.get('content-type')||''; if(!type.includes('application/json')) throw new Error(`JSON erwartet, aber ${type||'unbekannter Inhaltstyp'} empfangen (HTTP ${response.status}).`); const value=await response.json(); if(!response.ok) throw new Error(value.error||'Request failed'); return value; }
function setDirty(value=true){dirty=value; $('#status').textContent=value?'Nicht gespeicherte Änderungen':'Alle Änderungen gespeichert';}
function toast(message,error=false){const node=$('#toast');node.textContent=message;node.style.background=error?'#552326':'#183626';node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2500)}

async function loadScenarios(selectId){const list=await request('/api/scenarios');$('#scenario-select').innerHTML=list.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');$('#scenario-select').value=selectId||list[0]?.id;await loadScenario();}
async function loadScenario(){data=await request(`/api/scenarios/${$('#scenario-select').value}/editor`);selectedNation=null;selectedRegion=null;setDirty(false);renderAll();}
function renderAll(){renderMeta();renderNations();renderMap();showEmpty();}
function renderMeta(){const defs=[['name','Name'],['description','Beschreibung','textarea',true],['period','Zeitraum'],['startDate','Startdatum','date'],['minDate','Frühestes Datum','date'],['maxDate','Spätestes Datum','date'],['worldContext','KI-Weltkontext','textarea',true],['simulationRules','Simulationsregeln','textarea',true]];$('#meta-form').innerHTML=`<h2>Szenario</h2><div class="field-grid">${fields(data.scenario,defs)}</div>`;$('#meta-form').oninput=e=>{if(e.target.dataset.key){data.scenario[e.target.dataset.key]=e.target.value;setDirty();}}}
function renderNations(){const q=$('#nation-search').value.toLowerCase();$('#nation-list').innerHTML=Object.entries(data.nations).filter(([code,n])=>`${code} ${n.name}`.toLowerCase().includes(q)).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([code,n])=>`<div class="nation-item ${selectedNation===code?'active':''}" data-code="${code}"><i class="swatch" style="background:${n.color}"></i><span>${escapeHtml(n.name)}<small>${code} · ${ownedCount(code)} Gebiete</small></span></div>`).join('');}
function renderMap(){const map=data.regions;const svg=$('#editor-map');svg.setAttribute('viewBox',map.viewBox||`0 0 ${map.width} ${map.height}`);svg.innerHTML=map.regions.map(r=>`<path id="region-${escapeHtml(r.id)}" data-id="${escapeHtml(r.id)}" d="${escapeHtml(r.path)}" fill="${data.nations[r.nation_code]?.color||r.fill||'#888'}"><title>${escapeHtml(r.name)} · ${escapeHtml(data.nations[r.nation_code]?.name||r.nation_code)}</title></path>`).join('');}
function ownedCount(code){return data.regions.regions.filter(r=>r.nation_code===code).length}
function showEmpty(){$('#empty-detail').classList.remove('hidden');$('#nation-form').classList.add('hidden');$('#region-form').classList.add('hidden')}
function showNation(code){selectedNation=code;selectedRegion=null;renderNations();const n=data.nations[code], form=$('#nation-form');$('#empty-detail').classList.add('hidden');$('#region-form').classList.add('hidden');form.classList.remove('hidden');const defs=[['name','Name'],['color','Farbe','color'],['ideology','Ideologie'],['capital','Hauptstadt'],['leader_name','Anführer'],['leader_title','Titel'],['population','Bevölkerung','number'],['military_strength','Militärstärke','number']];form.innerHTML=`<h2>${escapeHtml(n.name)}</h2><div class="region-owner" style="border-color:${n.color}">${code} · ${ownedCount(code)} Gebiete</div><div class="field-grid">${fields(n,defs)}<label><input data-key="is_major_power" type="checkbox" ${n.is_major_power?'checked':''}> Großmacht</label></div><button type="button" class="danger" id="delete-nation">Land löschen</button>`;form.oninput=e=>{if(!e.target.dataset.key)return;n[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;setDirty();renderNations();if(e.target.dataset.key==='color'||e.target.dataset.key==='name')renderMap();};$('#delete-nation').onclick=()=>deleteNation(code);}
function showRegion(id){const r=data.regions.regions.find(item=>item.id===id);selectedRegion=id;document.querySelectorAll('#editor-map path').forEach(p=>p.classList.toggle('selected',p.dataset.id===id));const form=$('#region-form');$('#empty-detail').classList.add('hidden');$('#nation-form').classList.add('hidden');form.classList.remove('hidden');form.innerHTML=`<h2>Gebiet bearbeiten</h2><div class="region-owner" style="border-color:${data.nations[r.nation_code]?.color}">${escapeHtml(r.id)}</div><label>Name<input data-key="name" value="${escapeHtml(r.name)}"></label><label>Besitzer<select data-key="nation_code">${Object.entries(data.nations).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([c,n])=>`<option value="${c}" ${c===r.nation_code?'selected':''}>${escapeHtml(n.name)} (${c})</option>`).join('')}</select></label>`;form.oninput=e=>{if(!e.target.dataset.key)return;r[e.target.dataset.key]=e.target.value;setDirty();renderMap();renderNations();showRegion(id);};}
function assignRegion(id){const r=data.regions.regions.find(item=>item.id===id);if(!selectedNation)return toast('Bitte zuerst ein Land auswählen.',true);r.nation_code=selectedNation;setDirty();renderMap();renderNations();showRegion(id);}
function addNation(){const code=(prompt('Ländercode (2–5 Großbuchstaben/Ziffern):')||'').trim().toUpperCase();if(!/^[A-Z0-9]{2,5}$/.test(code))return toast('Ungültiger Ländercode.',true);if(data.nations[code])return toast('Dieser Code existiert bereits.',true);data.nations[code]={code,name:'Neues Land',ideology:'authoritarian',is_major_power:false,leader_name:'',leader_title:'',population:0,military_strength:0,color:'#d6a84b',capital:''};setDirty();showNation(code);}
function deleteNation(code){if(ownedCount(code))return toast('Weise zuerst alle Gebiete einem anderen Land zu.',true);if(!confirm(`${data.nations[code].name} wirklich löschen?`))return;delete data.nations[code];delete data.roadmaps[code];setDirty();selectedNation=null;renderNations();showEmpty();}
async function save(){try{await request(`/api/scenarios/${data.scenario.id}/editor`,{method:'PUT',body:JSON.stringify(data)});setDirty(false);toast('Szenario gespeichert.')}catch(error){toast(error.message,true)}}
async function createScenario(){const id=(prompt('Neue Szenario-ID (klein, ohne Leerzeichen):')||'').trim();if(!id)return;const name=(prompt('Anzeigename:')||id).trim();try{await request('/api/scenarios',{method:'POST',body:JSON.stringify({id,name,sourceId:data.scenario.id})});await loadScenarios(id);toast('Szenario wurde erstellt.')}catch(error){toast(error.message,true)}}

$('#scenario-select').onchange=()=>{if(!dirty||confirm('Ungespeicherte Änderungen verwerfen?'))loadScenario();else $('#scenario-select').value=data.scenario.id};$('#nation-search').oninput=renderNations;$('#nation-list').onclick=e=>{const item=e.target.closest('[data-code]');if(item)showNation(item.dataset.code)};$('#editor-map').onclick=e=>{const path=e.target.closest('path');if(!path)return;if($('#paint-mode').checked)assignRegion(path.dataset.id);else showRegion(path.dataset.id)};$('#add-nation').onclick=addNation;$('#save').onclick=save;$('#new-scenario').onclick=createScenario;window.onbeforeunload=()=>dirty?'Ungespeicherte Änderungen':undefined;loadScenarios('kaiserreich').catch(e=>toast(e.message,true));
